nome = input( "Digite seu nome: ")
idade = input("Digite sua idade: ")
peso = input("Digite seu peso: ")
print("----------------------------------------------------")
print ("Seu nome é ",nome,"\nSua idade é: ",idade, "\nSeu peso é: ",peso)
